# Generated by Django 4.0.3 on 2022-06-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', verbose_name='姓名')),
                ('img', models.ImageField(upload_to='./book', verbose_name='图片')),
            ],
        ),
    ]
