# Generated by Django 4.0.3 on 2022-05-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yuyan',
            new_name='cs',
        ),
        migrations.RenameModel(
            old_name='jinrong',
            new_name='economy',
        ),
        migrations.RenameModel(
            old_name='guanli',
            new_name='english',
        ),
        migrations.RenameModel(
            old_name='jisuanji',
            new_name='manage',
        ),
    ]
