# Generated by Django 4.0.3 on 2022-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_yuyan_cs_rename_jinrong_economy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='economy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='english',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
